name: worktree-base
type: wordpress
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.11"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
nodejs_version: "20"
web_environment:
  - WP_ENV=development
  - DB_NAME=db
  - DB_USER=db
  - DB_PASSWORD=db
  - DB_HOST=db
hooks:
  post-start:
    - exec: composer install --no-interaction
